<a href="https://colab.research.google.com/github/btramduong0810/dsc-mod-1-project-v2-1-online-ds-sp-000/blob/master/Data_Science_in_Action_The_Movie_Industry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Final Project Submission

* Student name: **BAO TRAM DUONG**
* Student pace: **SELF-PACED DATA SCIENCE PROGRAM**
* Scheduled project review date/time: 
* Instructor name: **JEFF HERMAN**
* Blog post URL:

# **Table of Contents**

**2.III. Data Analysis**

**3.  Data Visualization**

3.1  Budget

3.2  Runtime

3.3  Genre

3.4a  Release time: date

3.4b  Release time: month

3.4c  Release time: day

**4.  Conclusion and Future Work**

4.1  Summary of Findings

4.2  Actionable Insights

4.3  Future Works

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

/Users/baotramduong8/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [3]:
merged_df_1 = pd.read_csv('merged_df_1')
merged_df_1.head()

,Unnamed: 0,release_date,movie,production_budget,domestic_gross,worldwide_gross,release_year,studio,original_language,popularity,vote_average,vote_count,tconst,runtime_minutes,genres,profit
0,0,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,BV,en,30.579,6.4,8571,tt1298650,136.0,"Action,Adventure,Fantasy",635063875
1,1,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,BV,en,44.383,7.3,13457,tt2395427,141.0,"Action,Adventure,Sci-Fi",1072413963
2,2,2018-04-27,Avengers: Infinity War,300000000,678815482,2048134200,2018,BV,en,80.773,8.3,13948,tt4154756,149.0,"Action,Adventure,Sci-Fi",1748134200
3,3,2017-11-17,Justice League,300000000,229024295,655945209,2017,WB,en,34.953,6.2,7510,tt0974015,120.0,"Action,Adventure,Fantasy",355945209
4,4,2015-11-06,Spectre,300000000,200074175,879620923,2015,Sony,en,30.318,6.4,6719,tt2379713,148.0,"Action,Adventure,Thriller",579620923

In [4]:
merged_df_2 = pd.read_csv('merged_df_2')
merged_df_2.head()

,Unnamed: 0,release_date,release_year,movie,genre,source,production_method,creative_type,production_budget,domestic_gross,international_gross,worldwide_gross,profit
0,0,2010-06-18,2010,Toy Story 3,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000,415004880,653874642,1068879522,868879522
1,1,2010-03-05,2010,Alice in Wonderland,Adventure,Based on Fiction Book/Short Story,Animation/Live Action,Fantasy,200000000,334191110,691300000,1025491110,825491110
2,2,2010-05-07,2010,Iron Man 2,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,170000000,312433331,308723058,621156389,451156389
3,3,2010-06-30,2010,The Twilight Saga: Eclipse,Drama,Based on Fiction Book/Short Story,Live Action,Fantasy,68000000,300531751,405571077,706102828,638102828
4,4,2010-11-19,2010,Harry Potter and the Deathly Hallows:…,Adventure,Based on Fiction Book/Short Story,Animation/Live Action,Fantasy,125000000,296131568,660186220,956317788,831317788

In [5]:
len(merged_df_1)

1134

In [6]:
len(merged_df_2)

900

In [31]:
full_df = pd.merge(merged_df_1, merged_df_2, on='movie')

In [32]:
full_df.head(10)

,Unnamed: 0_x,release_date_x,movie,production_budget_x,domestic_gross_x,worldwide_gross_x,release_year_x,studio,original_language,popularity,...,release_year_y,genre,source,production_method,creative_type,production_budget_y,domestic_gross_y,international_gross,worldwide_gross_y,profit_y
0,1,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,BV,en,44.383,...,2015,Action,Based on Comic/Graphic Novel,Animation/Live Action,Super Hero,365000000,459005868,937093334,1396099202,1031099202
1,2,2018-04-27,Avengers: Infinity War,300000000,678815482,2048134200,2018,BV,en,80.773,...,2018,Action,Based on Comic/Graphic Novel,Animation/Live Action,Super Hero,300000000,678815482,1365725041,2044540523,1744540523
2,3,2017-11-17,Justice League,300000000,229024295,655945209,2017,WB,en,34.953,...,2017,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,300000000,229024295,426920914,655945209,355945209
3,4,2015-11-06,Spectre,300000000,200074175,879620923,2015,Sony,en,30.318,...,2015,Action,Based on Fiction Book/Short Story,Live Action,Contemporary Fiction,300000000,200074175,679426585,879500760,579500760
4,5,2012-07-20,The Dark Knight Rises,275000000,448139099,1084439099,2012,WB,en,26.220,...,2012,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,230000000,448139099,634089008,1082228107,852228107
5,6,2018-05-25,Solo: A Star Wars Story,275000000,213767512,393151347,2018,BV,en,29.502,...,2018,Adventure,Spin-Off,Animation/Live Action,Science Fiction,275000000,213767512,179383835,393151347,118151347
6,7,2012-03-09,John Carter,275000000,73058679,282778100,2012,BV,en,18.549,...,2012,Adventure,Based on Fiction Book/Short Story,Live Action,Science Fiction,263700000,73058679,209719421,282778100,19078100
7,8,2010-11-24,Tangled,260000000,200821936,586477240,2010,BV,en,21.511,...,2010,Musical,Based on Folk Tale/Legend/Fairytale,Digital Animation,Kids Fiction,260000000,200821936,384905155,585727091,325727091
8,9,2016-05-06,Captain America: Civil War,250000000,408084349,1140069413,2016,BV,en,39.137,...,2016,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,250000000,408084349,743834172,1151918521,901918521
9,10,2016-03-25,Batman v Superman: Dawn of Justice,250000000,330360194,867500281,2016,WB,en,28.088,...,2016,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,263000000,330360194,542034897,872395091,609395091

In [21]:
len(full_df)

692

In [33]:
full_df = full_df.drop(['Unnamed: 0_x', 'Unnamed: 0_y', 'release_date_y', 'release_year_y', 'tconst', 'production_budget_y', 'domestic_gross_y', 'worldwide_gross_y', 'profit_y'], axis=1)

In [34]:
full_df.head(10)

,release_date_x,movie,production_budget_x,domestic_gross_x,worldwide_gross_x,release_year_x,studio,original_language,popularity,vote_average,vote_count,runtime_minutes,genres,profit_x,genre,source,production_method,creative_type,international_gross
0,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,BV,en,44.383,7.3,13457,141.0,"Action,Adventure,Sci-Fi",1072413963,Action,Based on Comic/Graphic Novel,Animation/Live Action,Super Hero,937093334
1,2018-04-27,Avengers: Infinity War,300000000,678815482,2048134200,2018,BV,en,80.773,8.3,13948,149.0,"Action,Adventure,Sci-Fi",1748134200,Action,Based on Comic/Graphic Novel,Animation/Live Action,Super Hero,1365725041
2,2017-11-17,Justice League,300000000,229024295,655945209,2017,WB,en,34.953,6.2,7510,120.0,"Action,Adventure,Fantasy",355945209,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,426920914
3,2015-11-06,Spectre,300000000,200074175,879620923,2015,Sony,en,30.318,6.4,6719,148.0,"Action,Adventure,Thriller",579620923,Action,Based on Fiction Book/Short Story,Live Action,Contemporary Fiction,679426585
4,2012-07-20,The Dark Knight Rises,275000000,448139099,1084439099,2012,WB,en,26.220,7.7,13933,164.0,"Action,Thriller",809439099,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,634089008
5,2018-05-25,Solo: A Star Wars Story,275000000,213767512,393151347,2018,BV,en,29.502,6.6,3838,135.0,"Action,Adventure,Fantasy",118151347,Adventure,Spin-Off,Animation/Live Action,Science Fiction,179383835
6,2012-03-09,John Carter,275000000,73058679,282778100,2012,BV,en,18.549,6.1,3338,132.0,"Action,Adventure,Sci-Fi",7778100,Adventure,Based on Fiction Book/Short Story,Live Action,Science Fiction,209719421
7,2010-11-24,Tangled,260000000,200821936,586477240,2010,BV,en,21.511,7.5,6407,100.0,"Adventure,Animation,Comedy",326477240,Musical,Based on Folk Tale/Legend/Fairytale,Digital Animation,Kids Fiction,384905155
8,2016-05-06,Captain America: Civil War,250000000,408084349,1140069413,2016,BV,en,39.137,7.4,14000,147.0,"Action,Adventure,Sci-Fi",890069413,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,743834172
9,2016-03-25,Batman v Superman: Dawn of Justice,250000000,330360194,867500281,2016,WB,en,28.088,5.8,11991,151.0,"Action,Adventure,Fantasy",617500281,Action,Based on Comic/Graphic Novel,Live Action,Super Hero,542034897

In [35]:
full_df.to_csv('full_df')

# **3. DATA VISUALIZATION**

# **4. CONCLUSION & FUTURE WORKS**